### ISSUE TITLE
TypeError for my own treefile

### ISSUE THREAD

**Issue by Yung-Chien** [michaelmiyagi/QuIBL#11]
Hi @michaelmiyagi ,
I've finished the test of QuIBL and everything was okay. However, I got this error when I tried to run the script using my own tree file as below:

nohup: ignoring input
Traceback (most recent call last):
  File "/home1/x/software/QuIBL/QuIBL.py", line 337, in <module>
    inputReader(sys.argv[1])
  File "/home1/x/software/QuIBL/QuIBL.py", line 333, in inputReader
    outputFormatter(outputDict,inputDict)
  File "/home1/x/software/QuIBL/QuIBL.py", line 298, in outputFormatter
    trees=getTripBranches(readin_Newick(inputDict['treefile']),canonOut)
  File "/home1/x/software/QuIBL/QuIBL.py", line 62, in readin_Newick
    treeList.append(Tree(tree))
  File "/home1/x/miniconda2/lib/python2.7/site-packages/ete3/coretype/tree.py", line 210, in __init__
    read_newick(newick, root_node = self, format=format)
  File "/home1/x/miniconda2/lib/python2.7/site-packages/ete3/parser/newick.py", line 220, in read_newick
    if os.path.exists(newick):
  File "/home1/x/miniconda2/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: stat() argument 1 must be encoded string without null bytes, not str

Here is my input parameter file:

[Input]
treefile: /home1/x/pop.combine.pass.snpphylo.phylip.txt_phyml_boot_trees.txt
numdistributions: 2
likelihoodthresh: 0.01
numsteps: 50 
gradascentscalar: 0.5
totaloutgroup: RZ2-1
multiproc: True
maxcores:10

[Output]
OutputPath: testmyOut.csv

Maybe I need to change the path name or something else, but i'm still confused. Thanks in advance for your help.
Yung-Chien

**Comment by michaelmiyagi** [comment]
Hi Yung-Chien,

Based on the error message, it looks like there might be an error in your tree file- is it in this format (as in the sample tree file):

(Tree1);
(Tree2);
. . .

Can you check if this might be the issue?

Thanks,
Michael

**Comment by Yung-Chien** [comment]
Hi michaelmiyagi,

Yes the tree file format is the same as what you said. Meanwhile, I have one question that the format of example data is also like this. So how could I adjust my tree file to meet the requirement. Thanks a lot.

Yung-Chien
