### ISSUE TITLE
treefile format 

### ISSUE THREAD

**Issue by WeiweZhou** [michaelmiyagi/QuIBL#24]
Treefile:
((((((aff:0.0132867724,(((born:0.0046560450,((((macro:0.0052464938,marshalli:0.0009599543):0.0081675376,(paradox:0.0055104588,rex:0.0007087527):0.0016373502):0.0000023937,pearsoni:0.0137901542):0.0054230507,rsp:0.0036507056):0.0020701201):0.0034449837,ferr:0.0382550011):0.0000023937,thomasi:0.0057614312):0.0023778585):0.0104341927,rouxi:0.0150369822):0.0047179685,(hilde:0.0373886538,sin:0.0057867514):0.0010504414):0.0000027429,coel:0.0146196088):0.0028431129,luctus:0.0303481289):0.0035809346,har:0.0741173840,yx:0.0056946168);
((((aff:0.0052064274,luctus:0.0418196340):0.0039794553,pearsoni:0.0032177210):0.0006404153,(((coel:0.0055669378,rouxi:0.0029964469):0.0078547036,(((((ferr:0.0000023901,hilde:0.0120754962):0.0095575109,(macro:0.0069358953,marshalli:0.0041398365):0.0000022686):0.0000020417,paradox:0.0097662630):0.0049459883,(rex:0.0014304615,rsp:0.0007129524):0.0000023862):0.0058320175,yx:0.0054764646):0.0015750309):0.0022241770,(sin:0.0044664990,thomasi:0.0118295036):0.0004611714):0.0009618629):0.0050929017,born:0.0080866337,har:0.0229042966);
......
Inputfile.txt
[Input]
treefile: ./test.tre
numdistributions: 2
likelihoodthresh: 0.01
numsteps: 10
gradascentscalar: 0.5
totaloutgroup: har
multiproc: True
maxcores: 30
[Output]
OutputPath: ./test_output.csv
Run: python ../QuIBL.py 17indinputfile.txt 
ERROR:
Traceback (most recent call last):
  File "../QuIBL.py", line 338, in <module>
    inputReader(sys.argv[1])
  File "../QuIBL.py", line 334, in inputReader
    outputFormatter(outputDict,inputDict)
  File "../QuIBL.py", line 299, in outputFormatter
    trees=getTripBranches(readin_Newick(inputDict['treefile']),canonOut)
  File "../QuIBL.py", line 90, in getTripBranches
    tempTree.prune(triplet,preserve_branch_length=True)
  File "/share/home/songenhui/.local/lib/python2.7/site-packages/ete3/coretype/tree.py", line 531, in prune
    to_keep = set(_translate_nodes(self, *nodes))
  File "/share/home/songenhui/.local/lib/python2.7/site-packages/ete3/coretype/tree.py", line 2601, in _translate_nodes
    raise ValueError("Node names not found: "+str(notfound))
ValueError: Node names not found: ['aff']

**Comment by josh3397** [comment]
Hi,

I have the same error. Have you figured it out yet?
