### ISSUE TITLE
Problems with node names

### ISSUE THREAD

**Issue by pmomadeira** [michaelmiyagi/QuIBL#29]
Greetings @miriammiyagi and @nbedelman. I've been running into a problem while trying to run QuIBL on a dataset with 2 individuals per species. When trying to run the analysis I always end up with the error:

Traceback (most recent call last):
  File "/home/gareth/QuIBL/QuIBL.py", line 338, in <module>
    inputReader(sys.argv[1])
  File "/home/gareth/QuIBL/QuIBL.py", line 334, in inputReader
    outputFormatter(outputDict,inputDict)
  File "/home/gareth/QuIBL/QuIBL.py", line 299, in outputFormatter
    trees=getTripBranches(readin_Newick(inputDict['treefile']),canonOut)
  File "/home/gareth/QuIBL/QuIBL.py", line 90, in getTripBranches
    tempTree.prune(triplet,preserve_branch_length=True)
  File "/home/gareth/micromamba/envs/EckEnv/lib/python3.10/site-packages/ete3/coretype/tree.py", line 531, in prune
    to_keep = set(_translate_nodes(self, *nodes))
  File "/home/gareth/micromamba/envs/EckEnv/lib/python3.10/site-packages/ete3/coretype/tree.py", line 2601, in _translate_nodes
    raise ValueError("Node names not found: "+str(notfound))
ValueError: Node names not found: ['Ebic_f.0', 'Ebic_f.1']

I've tried changing the names so they wouldn't include . and even numbers (eg. Ebic_f_1 or Ebic_f_B) and that did not solve the problem. I was able to run the analysis on another dataset without any issues and I'm pretty sure the treefiles are similar between datasets, with the exception that this one has 2 samples per species. Could that be the issue? Or is there something that I might be missing? I should add that I am running this in Python3, the same way I did the analysis that did work.

If necessary I can share both the input and tree files I'm using.

Best regards,
Pedro Madeira

**Comment by chenmo11-cd** [comment]
maybe its the tree file you input do not contain all the nodename.
