### ISSUE TITLE
math domain error

### ISSUE THREAD

**Issue by stsmall** [michaelmiyagi/QuIBL#7]
HI @michaelmiyagi,
I have run QuIBL successfully on many sets of trees and occasionally I get an error. Is there a way to not calculate the Outgroup in the triplets?
thanks,
@stsmall

Python v3.7; anaconda, virt environment "allel"

$cat InputFile.X.txt                                                                                                                                                                          
[Input]
treefile: X.phyml.root.tre
numdistributions: 2
likelihoodthresh: 0.01
numsteps: 50
gradascentscalar: 0.5
totaloutgroup: outgroup_B
multiproc: True
maxcores:30

[Output]
OutputPath: X.quibl.50.csv

--------------------------------------------
stdout Error: 
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/s/ssmall2/anaconda3/envs/allel/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/afs/crc.nd.edu/user/s/ssmall2/anaconda3/envs/allel/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 272, in \_\_call\_\_
    return self.fn(*self.args, **self.kwargs)
  File "/afs/crc.nd.edu/user/s/ssmall2/anaconda3/envs/allel/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 600, in \_\_call\_\_
    return self.func(*args, **kwargs)
  File "/afs/crc.nd.edu/user/s/ssmall2/anaconda3/envs/allel/lib/python3.7/site-packages/joblib/parallel.py", line 256, in \_\_call\_\_
    for func, args, kwargs in self.items]
  File "/afs/crc.nd.edu/user/s/ssmall2/anaconda3/envs/allel/lib/python3.7/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/afs/crc.nd.edu/user/s/ssmall2/programs_that_work/QuIBL/QuIBL.py", line 278, in PLexMax
    lmbd,stepScale=gradAscent(branchData, XQList, cArray, pArray, lmbd, stepScale, numSteps, threshold)
  File "/afs/crc.nd.edu/user/s/ssmall2/programs_that_work/QuIBL/QuIBL.py", line 213, in gradAscent
    newLik=weightedLogLik(XQList,newcArray,newlmbd)
  File "/afs/crc.nd.edu/user/s/ssmall2/programs_that_work/QuIBL/QuIBL.py", line 141, in weightedLogLik
    L+=log(temp)
ValueError: math domain error
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/s/ssmall2/programs_that_work/QuIBL/QuIBL.py", line 340, in <module>
    inputReader(sys.argv[1])
  File "/afs/crc.nd.edu/user/s/ssmall2/programs_that_work/QuIBL/QuIBL.py", line 336, in inputReader
    outputFormatter(outputDict,inputDict)
  File "/afs/crc.nd.edu/user/s/ssmall2/programs_that_work/QuIBL/QuIBL.py", line 307, in outputFormatter
    tripletSet=Parallel(n_jobs=num_cores)(delayed(PLexMax)(triple,K,lthresh,numsteps,gAScalar) for triple in trees)
  File "/afs/crc.nd.edu/user/s/ssmall2/anaconda3/envs/allel/lib/python3.7/site-packages/joblib/parallel.py", line 1016, in \_\_call\_\_
    self.retrieve()
  File "/afs/crc.nd.edu/user/s/ssmall2/anaconda3/envs/allel/lib/python3.7/site-packages/joblib/parallel.py", line 908, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/afs/crc.nd.edu/user/s/ssmall2/anaconda3/envs/allel/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 554, in wrap_future_result
    return future.result(timeout=timeout)
  File "/afs/crc.nd.edu/user/s/ssmall2/anaconda3/envs/allel/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/afs/crc.nd.edu/user/s/ssmall2/anaconda3/envs/allel/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
ValueError: math domain error

**Comment by michaelmiyagi** [comment]
Thanks for letting us know- we've had some issues with underflow on the likelihood calculation for trees with many taxa, which could be the issue here. I can push an update to skip triplets with the canon outgroup as well.

**Comment by michaelmiyagi** [comment]
I've pushed an update so that it no longer looks for introgression in triplets containing the canonical outgroup (e.g. outgroup_B here). Please let me know if this works for you!
